CREATE TABLE [dm].[DimAssignmentScore]
(
	[GradingAssignmentScoreKey] bigint identity(1, 1) not null,
	[StudentKey] bigint NOT NULL,
	[StudentId] varchar(50) NULL,
	[TeachingGroupKey] bigint NULL,
	[SchoolInfoKey] bigint NULL,
	[GradingAssignmentKey] bigint NOT NULL,
	[StaffKey] bigint NOT NULL,
	[DateGraded] datetime NULL,
	[ExpectedScore] bit NULL,
	[ScorePoints] int NULL,
	[ScorePercent] numeric(5,2) NULL,
	[ScoreLetter] varchar(5) NULL,
	[ScoreDescription] varchar(255) NULL,
	[TeacherJudgement] varchar(255) NULL,
	[MarkInfoKey] bigint NULL,
	[AssignmentScoreIteration] varchar(255) NULL,
	[Status] varchar(50) null,
	[ValidFrom]       DATETIME2 (7)  NOT NULL,
    [ValidTo]         DATETIME2 (7)  NULL,
    [IsActive]        BIT NOT NULL,
    [CreatedOn]       DATETIME2 (7)  NOT NULL,
    [CreatedBy]       VARCHAR (256)  NOT NULL,
    [UpdatedOn]       DATETIME2 (7)  NULL,
    [UpdatedBy]       VARCHAR (256)   NOT NULL,
    [HashKey] varbinary(32) null
)
