CREATE TABLE [dm].[DimCalendarDate]
(
	[CalendarDateKey] bigint identity(1, 1) not null,
	[CalendarDate] date NULL,
	[CalendarSummaryKey] bigint NOT NULL,
	[SchoolInfoKey] bigint NOT NULL,
	[SchoolYear] varchar(4) NULL,
	[CalendarDateType] varchar(4) NULL,
	[CalendarDateNumber] int NULL,
	[StudentCountsTowardAttendance] varchar(3) NULL,
	[StudentAttendanceValue] numeric(4,1) NULL,
	[TeacherCountsTowardAttendance] numeric(4,1) NULL,
	[TeacherAttendanceValue] numeric(4,1) NULL,
	[AdministratorCountsTowardAttendance] numeric(4,1) NULL,
	[AdministratorAttendanceValue] numeric(4,1) NULL,
	[Status] varchar(50) null,
	[ValidFrom]       DATETIME2 (7)  NOT NULL,
    [ValidTo]         DATETIME2 (7)  NULL,
    [IsActive]        BIT NOT NULL,
    [CreatedOn]       DATETIME2 (7)  NOT NULL,
    [CreatedBy]       VARCHAR (256)  NOT NULL,
    [UpdatedOn]       DATETIME2 (7)  NULL,
    [UpdatedBy]       VARCHAR (256)   NOT NULL,
    [HashKey] varbinary(32) null
)
