CREATE TABLE [dm].[DimGradingInfo]
(
	[GradingAssignmentKey] bigint identity(1, 1) not null,
	[TeachingGroupKey] bigint NULL,
	[StudentKey] bigint NULL,
	[SchoolInfoKey] bigint NULL,
	[GradingCategory] varchar(255) NULL,
	[Description] varchar(1000) NOT NULL,
	[PointsPossible] int NULL,
	[CreateDate] datetime NULL,
	[DueDate] datetime NULL,
	[Weight] numeric(5,2) NULL,
	[MaxAttemptsAllowed] int NULL,
	[DetailedDescriptionURL] varchar(1000) NULL,
	[DetailedDescriptionBinary] varchar(8000) NULL,
	[AssessmentType] varchar(255) NULL,
	[LevelAssessed] varchar(255) NULL,
	[AssignmentPurpose] varchar(255) NULL,
	[Status] varchar(50) null,
	[ValidFrom]       DATETIME2 (7)  NOT NULL,
    [ValidTo]         DATETIME2 (7)  NULL,
    [IsActive]        BIT NOT NULL,
    [CreatedOn]       DATETIME2 (7)  NOT NULL,
    [CreatedBy]       VARCHAR (256)  NOT NULL,
    [UpdatedOn]       DATETIME2 (7)  NULL,
    [UpdatedBy]       VARCHAR (256)   NOT NULL,
    [HashKey] varbinary(32) null
)
