CREATE TABLE [dm].[DimMarkInfo]
(
	[MarkInfoKey] bigint identity(1, 1) not null,
	[SchoolInfoKey] bigint NOT NULL,
	[ValueName] varchar(255) NULL,
	[PercentageMinimum] numeric(5,2) NULL,
	[PercentageMaximum] numeric(5,2) NULL,
	[PercentagePassingGrade] numeric(5,2) NULL,
	[NumericPrecision] int NULL,
	[NumericScale] int NULL,
	[NumericLow] numeric(5,2) NULL,
	[NumericHigh] numeric(5,2) NULL,
	[NumericPassingGrade] numeric(5,2) NULL,
	[Narrative] varchar(255) NULL,
	[NarrativeMaximumSize] int NULL,
	[Status] varchar(50) null,
	[ValidFrom]       DATETIME2 (7)  NOT NULL,
    [ValidTo]         DATETIME2 (7)  NULL,
    [IsActive]        BIT NOT NULL,
    [CreatedOn]       DATETIME2 (7)  NOT NULL,
    [CreatedBy]       VARCHAR (256)  NOT NULL,
    [UpdatedOn]       DATETIME2 (7)  NULL,
    [UpdatedBy]       VARCHAR (256)   NOT NULL,
    [HashKey] varbinary(32) null
)
