CREATE TABLE [dm].[DimStudent] (
    [StudentKey]      BIGINT         IDENTITY (1, 1) NOT NULL,
    [StudentID]       VARCHAR (50)   NOT NULL,
    [FirstName]       VARCHAR (255)  NOT NULL,
    [LastName]        VARCHAR (255)  NOT NULL,
    [FullName]        VARCHAR (255)  NOT NULL,
    [Gender]          VARCHAR (10)   NOT NULL,
    [DOB]             DATE           NOT NULL,
    [YearLevel]       CHAR (2)       NOT NULL,
    [Class]           VARCHAR (50)   NOT NULL,
    [YearOfEnrolment] VARCHAR (50)   NOT NULL,
    [Boarder]         VARCHAR (50)   NOT NULL,
    [HomePostCode]    VARCHAR (50)   NOT NULL,
    [Disability]      VARCHAR (50)   NOT NULL,
    [Status]          VARCHAR (50)   NOT NULL,
    [ValidFrom]       DATETIME2 (7)  CONSTRAINT [DF__DimStuden__Valid__370627FE] DEFAULT (getdate()) NOT NULL,
    [ValidTo]         DATETIME2 (7)  NULL,
    [IsActive]        BIT            CONSTRAINT [DF__DimStuden__IsAct__37FA4C37] DEFAULT ((1)) NOT NULL,
    [CreatedOn]       DATETIME2 (7)  CONSTRAINT [DF__DimStuden__Creat__38EE7070] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]       VARCHAR (256)  CONSTRAINT [DF__DimStuden__Creat__39E294A9] DEFAULT (suser_sname()) NOT NULL,
    [UpdatedOn]       DATETIME2 (7)  CONSTRAINT [DF__DimStuden__Updat__3AD6B8E2] DEFAULT (suser_sname()) NULL,
    [UpdatedBy]       VARCHAR (256)  CONSTRAINT [DF__DimStuden__Updat__3BCADD1B] DEFAULT (getdate()) NOT NULL,
    [HashKey]         VARBINARY (32) NOT NULL
);

