CREATE TABLE [dm].[DimSectionInfo] (
	[SectionInfoKey] bigint identity(1, 1) not null,
	[SchoolCourseInfoKey] bigint null,
	[SectionInfoId] varchar(50) null,
	[Description] varchar(255) null,
	[SchoolYear] numeric(4,0) null,
	[TermInfoKey] bigint null,
	[MediumOfInstructionMain] varchar(255) null,
	[MediumOfInstructionOther] varchar(255) null,
	[LanguageOfInstructionMain] varchar(255) null,
	[LanguageOfInstructionOther] varchar(255) null,
	[LocationOfInstructionMain] varchar(255) null,
	[LocationOfInstructionOther] varchar(255) null,
	[IsSummerSchool] varchar(3) null,
	[CourseSectionCode] varchar(255) null,
	[SectionCode] varchar(255) null,
	[IsCountForAttendance] varchar(3) null,
	[Status] varchar(50) null,
	[ValidFrom] datetime2(7) constraint [DF_DimSecInfo_Valid_A85628A1] default (getdate()) not null,
    [ValidTo] datetime2(7) null,
    [IsActive] bit constraint [DF__DimSecInfo__IsAct__37FA4C37] default ((1)) not null,
    [CreatedOn] datetime2(7) constraint [DF__DimSecInfo__Creat__38EE7070] default (getdate()) not null,
    [CreatedBy] varchar(256) constraint [DF__DimSecInfo__Creat__39E294A9] default (suser_sname()) not null,
    [UpdatedOn] datetime2(7) constraint [DF__DimSecInfo__Updat__3AD6B8E2] default (suser_sname()) null,
    [UpdatedBy] varchar(256) constraint [DF__DimSecInfo__Updat__3BCADD1B] default (getdate()) not null,
    [HashKey] varbinary(32) null
);