CREATE TABLE [dm].[DimStudentScoreJAS]
(
	[StudentScoreJASKey] bigint identity(1, 1) not null,
	[SchoolYear] numeric(4,0) NOT NULL,
	[TermInfoKey] bigint NOT NULL,
	[LocalTermCode] varchar(255) NULL,
	[StudentKey] bigint NOT NULL,
	[StudentStateProvinceId] varchar(255) NULL,
	[StudentLocalId] varchar(255) NULL,
	[YearLevel] varchar(10) NULL,
	[TeachingGroupKey] bigint NOT NULL,
	[ClassLocalId] varchar(255) NULL,
	[StaffKey] bigint NULL,
	[StaffLocalId] varchar(255) NULL,
	[LearningStandardList] varchar(1000) NULL,
	[CurriculumCode] varchar(255) NULL,
	[CurriculumNodeCode] varchar(255) NULL,
	[Score] varchar(255) NULL,
	[SpecialCircumstanceLocalCode] varchar(255) NULL,
	[ManagedPathwayLocalCode] varchar(255) NULL,
	[SchoolInfoRefId] varchar(255) NULL,
	[SchoolLocalId] varchar(255) NULL,
	[SchoolCommonwealthId] varchar(255) NULL,
	[Status] varchar(50) null,
	[ValidFrom]       DATETIME2 (7)  NOT NULL,
    [ValidTo]         DATETIME2 (7)  NULL,
    [IsActive]        BIT NOT NULL,
    [CreatedOn]       DATETIME2 (7)  NOT NULL,
    [CreatedBy]       VARCHAR (256)  NOT NULL,
    [UpdatedOn]       DATETIME2 (7)  NULL,
    [UpdatedBy]       VARCHAR (256)   NOT NULL,
    [HashKey] varbinary(32) null

)
