CREATE TABLE [dm].[DimSectionInfo] (
	[SectionInfoKey] bigint identity(1, 1) not null,
	[SchoolCourseInfoKey] bigint null,
	[SectionInfoId] varchar(50) null,
	[Description] varchar(255) null,
	[SchoolYear] numeric(4,0) null,
	[TermInfoKey] bigint null,
	[MediumOfInstructionMain] varchar(255) null,
	[MediumOfInstructionOther] varchar(255) null,
	[LanguageOfInstructionMain] varchar(255) null,
	[LanguageOfInstructionOther] varchar(255) null,
	[LocationOfInstructionMain] varchar(255) null,
	[LocationOfInstructionOther] varchar(255) null,
	[IsSummerSchool] varchar(3) null,
	[CourseSectionCode] varchar(255) null,
	[SectionCode] varchar(255) null,
	[IsCountForAttendance] varchar(3) null,
	[Status] varchar(50) null,
	[ValidFrom]       DATETIME2 (7)  NOT NULL,
    [ValidTo]         DATETIME2 (7)  NULL,
    [IsActive]        BIT NOT NULL,
    [CreatedOn]       DATETIME2 (7)  NOT NULL,
    [CreatedBy]       VARCHAR (256)  NOT NULL,
    [UpdatedOn]       DATETIME2 (7)  NULL,
    [UpdatedBy]       VARCHAR (256)   NOT NULL,
    [HashKey] varbinary(32) null
);