CREATE TABLE [dm].[DimStaff] (
    [StaffKey] bigint identity(1, 1) not null,
    [StaffId] varchar(50) null,
    [StateProvinceId] varchar(20) null,
    [FirstName] varchar(255) null,
    [LastName] varchar(255) null,
    [MiddleName] varchar(255) null,
    [OtherNames] varchar(255) null,
    [Title] varchar(50) null,
    [EmploymentStatus] varchar(1) null,
    [IndigenousStatus] smallint null,
    [Sex] varchar(10) null,
    [BirthDate] date null,
    [DateOfDeath] date null,
    [Deceased] varchar(2) null,
    [BirthDateVerification] varchar(50) null,
    [PlaceOfBirth] varchar(50) null,
    [StateOfBirth] varchar(50) null,
    [CountryOfBirth] varchar(50) null,
    [CountryOfCitizenship] varchar(50) null,
    [CountryOfCitizenship2] varchar(50) null,
    [CountryOfResidency] varchar(50) null,
    [CountryOfResidency2] varchar(50) null,
    [CountryArrivalDate] date null,
    [AustralianCitizenshipStatus] varchar(2) null,
    [EnglishProficiency] smallint null,
    [MainLanguageSpokenAtHome] varchar(50) null,
    [SecondLanguage] varchar(50) null,
    [OtherLanguage] varchar(50) null,
    [DwellingArrangement] varchar(50) null,
    [Religion] varchar(50) null,
    [ReligionEvent1] varchar(50) null,
    [ReligionEvent1Date] date null,
    [ReligionEvent2] varchar(50) null,
    [ReligionEvent2Date] date null,
    [ReligionEvent3] varchar(50) null,
    [ReligionEvent3Date] date null,
    [ReligiousRegion] varchar(50) null,
    [PermanentResident] varchar(2) null,
    [VisaSubClass] varchar(255) null,
    [VisaStatisticalCode] varchar(5) null,
    [TypeEmail1Description] varchar(2) null,
    [Email1] varchar(50) null,
    [TypeEmail2Description] varchar(2) null,
    [Email2] varchar(50) null,
    [Telephone1TypeDescription] varchar(2) null,
    [Telephone1] varchar(50) null,
    [Telephone2TypeDescription] varchar(2) null,
    [Telephone2] varchar(50) null,
    [Status]          VARCHAR (50)   NOT NULL,
    [ValidFrom]       DATETIME2 (7)  NOT NULL,
    [ValidTo]         DATETIME2 (7)  NULL,
    [IsActive]        BIT NOT NULL,
    [CreatedOn]       DATETIME2 (7)  NOT NULL,
    [CreatedBy]       VARCHAR (256)  NOT NULL,
    [UpdatedOn]       DATETIME2 (7)  NULL,
    [UpdatedBy]       VARCHAR (256)   NOT NULL,
    [HashKey] varbinary(32) null
);