CREATE TABLE [dm].[DimStudentGrade]
(
	[StudentGradePK] bigint NOT NULL,
	[StudentKey] bigint NOT NULL,
	[HomeGroup] varchar(255) NULL,
	[YearLevel] varchar(10) NULL,
	[TeachingGroupShortName] varchar(255) NULL,
	[TeachingGroupKey] bigint NULL,
	[StaffKey] bigint NOT NULL,
	[SchoolInfoKey] bigint NOT NULL,
	[TermInfoKey] bigint NOT NULL,
	[Description] varchar(255) NULL,
	[GradePercentage] numeric(5,2) NULL,
	[GradeNumeric] numeric(5,2) NULL,
	[GradeLetter] varchar(10) NULL,
	[GradeNarrative] varchar(255) NULL,
	[MarkInfoKey] bigint NOT NULL,
	[TeacherJudgement] varchar(255) NULL,
	[TermSpan] varchar(4) NULL,
	[SchoolYear] varchar(4) NULL,
	[Status] varchar(50) null,
	[ValidFrom] datetime2(7) constraint [DF_DimStGrade_Valid_A85628A1] default (getdate()) not null,
    [ValidTo] datetime2(7) null,
    [IsActive] bit constraint [DF__DimStGrade__IsAct__37FA4C37] default ((1)) not null,
    [CreatedOn] datetime2(7) constraint [DF__DimStGrade__Creat__38EE7070] default (getdate()) not null,
    [CreatedBy] varchar(256) constraint [DF__DimStGrade__Creat__39E294A9] default (suser_sname()) not null,
    [UpdatedOn] datetime2(7) constraint [DF__DimStGrade__Updat__3AD6B8E2] default (suser_sname()) null,
    [UpdatedBy] varchar(256) constraint [DF__DimStGrade__Updat__3BCADD1B] default (getdate()) not null,
    [HashKey] varbinary(32) null
)
