CREATE TABLE [dm].[DimSchoolInfo]
(
	[SchoolInfoKey] bigint NOT NULL,
	[SchooldInfoId] varchar(50) NULL,
	[StateProvinceId] varchar(50) NULL,
	[CommonwealthId] varchar(50) NULL,
	[ParentCommonwealthId] varchar(50) NULL,
	[ACARAId] varchar(50) NULL,
	[SchoolName] varchar(255) NOT NULL,
	[LEAInfoRefId] varchar(50) NULL,
	[OtherLEAId] varchar(50) NULL,
	[SIF_RefObject] varchar(7) NOT NULL,
	[SchoolDistrict] varchar(255) NULL,
	[SchoolDistrictId] varchar(50) NULL,
	[SchoolType] varchar(255) NULL,
	[SchoolURL] varchar(1000) NULL,
	[PrincipalInfoType] varchar(50) NULL,
	[PrincipalInfoTitle] varchar(50) NULL,
	[PrincipalInfoFamilyName] varchar(255) NULL,
	[PrincipalInfoGivenName] varchar(255) NULL,
	[PrincipalInfoMiddleName] varchar(255) NULL,
	[PrincipalInfoSuffix] varchar(50) NULL,
	[PrincipalInfoFullName] varchar(255) NULL,
	[PrincipalInfoContactTitle] varchar(255) NULL,
	[Telephone1] varchar(50) NULL,
	[Telephone1TypeDescription] varchar (2)   NULL,
	[Telephone2] varchar(50) NULL,
	[Telephone2TypeDescription] varchar (2)   NULL,
	[SessionType] varchar(4) NULL,
	[ARIA] float NULL,
	[OperationalStatus] varchar(1) NULL,
	[FederalElectorate] varchar(3) NULL,
	[SchoolSector] varchar(3) NULL,
	[IndependentSchool] varchar(1) NULL,
	[NonGovSystemicStatus] varchar(1) NULL,
	[SchoolSystemType] varchar(4) NULL,
	[ReligiousAfiliationGroup] varchar(4) NULL,
	[SchoolGeographicLocation] varchar(10) NULL,
	[LocalGovernmentArea] varchar(255) NULL,
	[JurisdictionLowerHouse] varchar(255) NULL,
	[SLA] varchar(10) NULL,
	[SchoolCoEdStatus] varchar(1) NULL,
	[BoardingSchoolStatus] varchar(1) NULL,
	[EntityOpen] date NULL,
	[EntityClose] date NULL,
	[SchoolTimeZone] varchar(10) NULL
)
