CREATE TABLE [dm].[DimStaff] (
    [StaffKey] bigint identity(1, 1) not null,
    [StaffId] varchar(50) null,
    [StateProvinceId] varchar(20) null,
    [FirstName] varchar(255) null,
    [LastName] varchar(255) null,
    [MiddleName] varchar(255) null,
    [OtherNames] varchar(255) null,
    [Title] varchar(50) null,
    [EmploymentStatus] varchar(1) null,
    [IndigenousStatus] smallint null,
    [Sex] varchar(10) null,
    [BirthDate] date null,
    [DateOfDeath] date null,
    [Deceased] varchar(2) null,
    [BirthDateVerification] varchar(50) null,
    [PlaceOfBirth] varchar(50) null,
    [StateOfBirth] varchar(50) null,
    [CountryOfBirth] varchar(50) null,
    [CountryOfCitizenship] varchar(50) null,
    [CountryOfCitizenship2] varchar(50) null,
    [CountryOfResidency] varchar(50) null,
    [CountryOfResidency2] varchar(50) null,
    [CountryArrivalDate] date null,
    [AustralianCitizenshipStatus] varchar(2) null,
    [EnglishProficiency] smallint null,
    [MainLanguageSpokenAtHome] varchar(50) null,
    [SecondLanguage] varchar(50) null,
    [OtherLanguage] varchar(50) null,
    [DwellingArrangement] varchar(50) null,
    [Religion] varchar(50) null,
    [ReligionEvent1] varchar(50) null,
    [ReligionEvent1Date] date null,
    [ReligionEvent2] varchar(50) null,
    [ReligionEvent2Date] date null,
    [ReligionEvent3] varchar(50) null,
    [ReligionEvent3Date] date null,
    [ReligiousRegion] varchar(50) null,
    [PermanentResident] varchar(2) null,
    [VisaSubClass] varchar(255) null,
    [VisaStatisticalCode] varchar(5) null,
    [TypeEmail1Description] varchar(2) null,
    [Email1] varchar(50) null,
    [TypeEmail2Description] varchar(2) null,
    [Email2] varchar(50) null,
    [Telephone1TypeDescription] varchar(2) null,
    [Telephone1] varchar(50) null,
    [Telephone2TypeDescription] varchar(2) null,
    [Telephone2] varchar(50) null,
    [Status] varchar(50) null,
    [ValidFrom] datetime2(7) constraint [DF_DimStaff_Valid_A85628A1] default (getdate()) not null,
    [ValidTo] datetime2(7) null,
    [IsActive] bit constraint [DF__DimStaff__IsAct__37FA4C37] default ((1)) not null,
    [CreatedOn] datetime2(7) constraint [DF__DimStaff__Creat__38EE7070] default (getdate()) not null,
    [CreatedBy] varchar(256) constraint [DF__DimStaff__Creat__39E294A9] default (suser_sname()) not null,
    [UpdatedOn] datetime2(7) constraint [DF__DimStaff__Updat__3AD6B8E2] default (suser_sname()) null,
    [UpdatedBy] varchar(256) constraint [DF__DimStaff__Updat__3BCADD1B] default (getdate()) not null,
    [HashKey] varbinary(32) null
);