CREATE TABLE [dm].[DimStudentGrade]
(
	[StudentGradePK] bigint identity(1, 1) not null,
	[StudentKey] bigint NOT NULL,
	[HomeGroup] varchar(255) NULL,
	[YearLevel] varchar(10) NULL,
	[TeachingGroupShortName] varchar(255) NULL,
	[TeachingGroupKey] bigint NULL,
	[StaffKey] bigint NOT NULL,
	[SchoolInfoKey] bigint NOT NULL,
	[TermInfoKey] bigint NOT NULL,
	[Description] varchar(255) NULL,
	[GradePercentage] numeric(5,2) NULL,
	[GradeNumeric] numeric(5,2) NULL,
	[GradeLetter] varchar(10) NULL,
	[GradeNarrative] varchar(255) NULL,
	[MarkInfoKey] bigint NOT NULL,
	[TeacherJudgement] varchar(255) NULL,
	[TermSpan] varchar(4) NULL,
	[SchoolYear] varchar(4) NULL,
	[Status] varchar(50) null,
	[ValidFrom]       DATETIME2 (7)  NOT NULL,
    [ValidTo]         DATETIME2 (7)  NULL,
    [IsActive]        BIT NOT NULL,
    [CreatedOn]       DATETIME2 (7)  NOT NULL,
    [CreatedBy]       VARCHAR (256)  NOT NULL,
    [UpdatedOn]       DATETIME2 (7)  NULL,
    [UpdatedBy]       VARCHAR (256)   NOT NULL,
    [HashKey] varbinary(32) null
)
