CREATE TABLE [dm].[DimStudent] (
    [StudentKey]        BIGINT         IDENTITY (1, 1) NOT NULL,
    
    [StudentID]       	VARCHAR (20)                ,
    StateProvinceId	    Varchar(20)                 ,
    NationalUniqueStudentIdentifier	VARCHAR (20)    ,

    [FirstName]       	VARCHAR (255)               ,
    [LastName]        	VARCHAR (255)               ,
    [MiddleName]        VARCHAR (255)               NULL,
    OtherNames	        VARCHAR (255)               NULL,
    ProjectedGraduationYear	Numeric(4,0)            NULL,
    OnTimeGraduationYear	Numeric(4,0)            NULL,
    GraduationDate	    Date                        NULL,
    AcceptableUsePolicy	VARCHAR (2)                 NULL,
    GiftedTalented	    VARCHAR (2)                 NULL    ,
    EconomicDisadvantage	VARCHAR (2)             NULL,
    ESL	                VARCHAR (2)                 NULL                ,
    ESLDateAssessed	    Date                        NULL    ,
    YoungCarersRole	    VARCHAR (2)                 NULL    ,
    Disability	        VARCHAR (2)                 NULL        ,
    IntegrationAide	    VARCHAR (2)                 NULL    ,
    EducationSupport	VARCHAR (2)                 NULL,
    HomeSchooledStudent	VARCHAR (2)                 NULL,
    IndependentStudent	VARCHAR (2)                 NULL,
    Sensitive	        VARCHAR (2)                 NULL        ,
    OfflineDelivery	    VARCHAR (2)                 NULL    ,
    ESLSupport	        VARCHAR (2)                 NULL        ,
    PrePrimaryEducation	VARCHAR (50)                NULL,
    PrePrimaryEducationHours	VARCHAR (2)         NULL,
    FirstAUSchoolEnrollment	Date                    NULL,                                 
    Typeemail1description	VARCHAR (20)            Null ,
    Email1	                Varchar(50)             Null ,
    typeemail2description	VARCHAR (20)            Null ,
    Email2	                Varchar(50)             Null     ,
    Telephone1	            Varchar(50)             Null ,
    Telephone1TypeDescription	VARCHAR (20)        Null ,
    Mobilephone	             Varchar(50)            Null ,
    OtherPhone               Varchar(50)            Null ,                    
    IndigenousStatus	Smallint                    ,
    Sex	                VARCHAR (10)                     ,
    BirthDate	        DATE                             ,
    DateOfDeath	        DATE                       NULL        ,
    Deceased	        VARCHAR (2)                NULL        ,
    BirthDateVerification	VARCHAR (50)           NULL,
    PlaceOfBirth	VARCHAR (50)                   NULL,
    StateOfBirth	VARCHAR (50)                   NULL,
    CountryOfBirth	VARCHAR (50)                   NULL,
    CountriesOfCitizenship	VARCHAR (50)           NULL,
    CountriesOfResidency	VARCHAR (50)           NULL,
    CountryArrivalDate	DATE                       NULL,
    AustralianCitizenshipStatus	VARCHAR (2)        NULL,
    EnglishProficiency	Smallint                   NULL,
    MainLanguageSpokenAtHome	VARCHAR (50)       NULL,
    SecondLanguage	VARCHAR (50)                   NULL,
    OtherLanguage	VARCHAR (50)                   NULL,
    DwellingArrangement	VARCHAR (50)               NULL,
    Religion	    VARCHAR (50)                   NULL    ,
    ReligionEvent1	VARCHAR (50)                   NULL,
    ReligionEvent1Date	Date                       NULL,
    ReligionEvent2	VARCHAR (50)                   NULL,
    ReligionEvent2Date	Date                       NULL,
    ReligionEvent3	VARCHAR (50)                   NULL,
    ReligionEvent3Date	Date                       NULL,
    ReligiousRegion	VARCHAR (50)                   NULL,
    PermanentResident	VARCHAR (2)                NULL ,
    VisaSubClass	VARCHAR (255)                  NULL ,
    VisaStatisticalCode	Varchar (5)                NULL ,
    VisaNumber	    VARCHAR (50)                   NULL     ,
    VisaGrantDate	Date                           NULL ,
    VisaExpiryDate	Date                           NULL ,
    VisaConditions	VARCHAR (255)                  NULL ,
    VisaStudyEntitlement	VARCHAR (255)          NULL ,
    ATEExpiryDate	Date                           NULL ,
    ATEStartDate	Date                           NULL ,
    PassportNumber	VARCHAR (20)                   NULL ,
    PassportExpiryDate	Date                       NULL ,
    PassportCountry	VARCHAR (20)                   NULL ,
    LBOTE	        VARCHAR (2)                    NULL         ,
    InterpreterRequired	VARCHAR (2)                NULL ,
    ImmunisationCertificateStatus	VARCHAR (50)   NULL ,
    CulturalBackground	VARCHAR (50)               NULL ,
    MaritalStatus	VARCHAR (50)                   NULL ,
    MedicareNumber	Numeric(12,0)                  NULL ,
    MedicarePositionNumber	Numeric(1,0)           NULL ,
    MedicareCardHolderName	VARCHAR (50)           NULL ,
    PrivateHealthInsurance	VARCHAR (50)           NULL ,


    [Status]          VARCHAR (50)   NOT NULL,
    [ValidFrom]       DATETIME2 (7)  CONSTRAINT [DF__DimStuden__Valid__370627FE] DEFAULT (getdate()) NOT NULL,
    [ValidTo]         DATETIME2 (7)  NULL,
    [IsActive]        BIT            CONSTRAINT [DF__DimStuden__IsAct__37FA4C37] DEFAULT ((1)) NOT NULL,
    [CreatedOn]       DATETIME2 (7)  CONSTRAINT [DF__DimStuden__Creat__38EE7070] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]       VARCHAR (256)  CONSTRAINT [DF__DimStuden__Creat__39E294A9] DEFAULT (suser_sname()) NOT NULL,
    [UpdatedOn]       DATETIME2 (7)  CONSTRAINT [DF__DimStuden__Updat__3AD6B8E2] DEFAULT (suser_sname()) NULL,
    [UpdatedBy]       VARCHAR (256)  CONSTRAINT [DF__DimStuden__Updat__3BCADD1B] DEFAULT (getdate()) NOT NULL,
    [HashKey]         VARBINARY (32) NOT NULL
);

