CREATE TABLE [dm].[DimTermInfo] (
	[TermInfoKey] bigint identity(1, 1) not null,
	[SchoolInfoKey] bigint null, 
	[SchoolYearType] numeric(4,0) null, 
	[StartDate] date null, 
	[EndDate] date null, 
	[Description] varchar(255) null, 
	[RelativeDuration] numeric(10,4) null, 
	[TermCode] varchar(50) null, 
	[Track] varchar(100) null, 
	[TermSpan] varchar(20) null, 
	[MarketingTerm] varchar(2) null, 
	[SchedulingTerm] varchar(2) null, 
	[AttendanceTerm] varchar(2) null, 
	[Status] varchar(50) null,
	[ValidFrom] datetime2(7) constraint [DF_DimTermInfo_Valid_A85628A1] default (getdate()) not null,
    [ValidTo] datetime2(7) null,
    [IsActive] bit constraint [DF__DimTermInfo__IsAct__37FA4C37] default ((1)) not null,
    [CreatedOn] datetime2(7) constraint [DF__DimTermInfo__Creat__38EE7070] default (getdate()) not null,
    [CreatedBy] varchar(256) constraint [DF__DimTermInfo__Creat__39E294A9] default (suser_sname()) not null,
    [UpdatedOn] datetime2(7) constraint [DF__DimTermInfo__Updat__3AD6B8E2] default (suser_sname()) null,
    [UpdatedBy] varchar(256) constraint [DF__DimTermInfo__Updat__3BCADD1B] default (getdate()) not null,
    [HashKey] varbinary(32) null
);