CREATE TABLE [dm].[DimTeachingGroup] (
	[TeachingGroupKey] bigint identity(1, 1) not null,
	[SchoolYear] numeric(4,0) null,
	[TeachingGroupId] varchar(50) null,
	[ShortName] varchar(20) null,
	[LongName] varchar(255) null,
	[GroupType] varchar(50) null,
	[SetNumber] int null,
	[BlockNumber] int null,
	[CurriculumLevel] varchar(255) null,
	[SchoolKey] bigint null,
	[SchoolId] varchar(50) null,
	[SchoolCourseKey] bigint null,
	[SchoolCourseId] varchar(50) null,
	[KeyLearningArea] varchar(20) null,
	[Semester] varchar(50) null,
	[MinClassSize] int null,
	[MaxClassSize] int null,
	[Status]          VARCHAR (50)   NOT NULL,
    [ValidFrom]       DATETIME2 (7)  NOT NULL,
    [ValidTo]         DATETIME2 (7)  NULL,
    [IsActive]        BIT NOT NULL,
    [CreatedOn]       DATETIME2 (7)  NOT NULL,
    [CreatedBy]       VARCHAR (256)  NOT NULL,
    [UpdatedOn]       DATETIME2 (7)  NULL,
    [UpdatedBy]       VARCHAR (256)   NOT NULL,
    [HashKey] varbinary(32) null
);