CREATE TABLE [dm].[DimTeachingGroup] (
	[TeachingGroupKey] bigint identity(1, 1) not null,
	[SchoolYear] numeric(4,0) null,
	[TeachingGroupId] varchar(50) null,
	[ShortName] varchar(20) null,
	[LongName] varchar(255) null,
	[GroupType] varchar(50) null,
	[SetNumber] int null,
	[BlockNumber] int null,
	[CurriculumLevel] varchar(255) null,
	[SchoolKey] bigint null,
	[SchoolId] varchar(50) null,
	[SchoolCourseKey] bigint null,
	[SchoolCourseId] varchar(50) null,
	[KeyLearningArea] varchar(20) null,
	[Semester] varchar(50) null,
	[MinClassSize] int null,
	[MaxClassSize] int null,
	[Status] varchar(50) null,
	[ValidFrom] datetime2(7) constraint [DF_DimTGroup_Valid_A85628A1] default (getdate()) not null,
    [ValidTo] datetime2(7) null,
    [IsActive] bit constraint [DF__DimTGroup__IsAct__37FA4C37] default ((1)) not null,
    [CreatedOn] datetime2(7) constraint [DF__DimTGroup__Creat__38EE7070] default (getdate()) not null,
    [CreatedBy] varchar(256) constraint [DF__DimTGroup__Creat__39E294A9] default (suser_sname()) not null,
    [UpdatedOn] datetime2(7) constraint [DF__DimTGroup__Updat__3AD6B8E2] default (suser_sname()) null,
    [UpdatedBy] varchar(256) constraint [DF__DimTGroup__Updat__3BCADD1B] default (getdate()) not null,
    [HashKey] varbinary(32) null
);