CREATE TABLE [dm].[DimTermInfo] (
	[TermInfoKey] bigint identity(1, 1) not null,
	[SchoolInfoKey] bigint null, 
	[SchoolYearType] numeric(4,0) null, 
	[StartDate] date null, 
	[EndDate] date null, 
	[Description] varchar(255) null, 
	[RelativeDuration] numeric(10,4) null, 
	[TermCode] varchar(50) null, 
	[Track] varchar(100) null, 
	[TermSpan] varchar(20) null, 
	[MarketingTerm] varchar(2) null, 
	[SchedulingTerm] varchar(2) null, 
	[AttendanceTerm] varchar(2) null, 
	[Status] varchar(50) null,
	[ValidFrom]       DATETIME2 (7)  NOT NULL,
    [ValidTo]         DATETIME2 (7)  NULL,
    [IsActive]        BIT NOT NULL,
    [CreatedOn]       DATETIME2 (7)  NOT NULL,
    [CreatedBy]       VARCHAR (256)  NOT NULL,
    [UpdatedOn]       DATETIME2 (7)  NULL,
    [UpdatedBy]       VARCHAR (256)   NOT NULL,
    [HashKey] varbinary(32) null
);