name: Build & Publish Component

on: 
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      path:
        required: true
        type: string        
      package-name:
        required: true
        type: string       

env:
  DOTNET_VERSION: '3.1.x'
jobs:
  build-component:
    name: Publish ${{name}}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{path}}
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies (dotnet restore)
      run: dotnet restore      

    - name: Release Build
      run: dotnet publish --no-restore --configuration Release --output ${{package-name}}

    - name: Publish Artifact
    - uses: actions/upload-artifact@v2
      with:
        name: ${{package-name}}    
        path: ${{package-name}}





