inputs = {
  prefix                               = "ads"              # All azure resources will be prefixed with this
  domain                                = "moqdigital.com.au"              # Used when configuring AAD config for Azure functions 
  tenant_id                             = "e73431a8-a744-43da-8f5e-68fc1dca7a5b"           # This is the Azure AD tenant ID
  subscription_id                       = "cd486ba9-eef3-466d-b16c-7f1b2941ae9d"     # The azure subscription id to deploy to
  resource_location                     = "Australia East"        # The location of the resources
  resource_group_name                   = "sifgofast"             # The resource group all resources will be deployed to
  owner_tag                             = "lbravo"                # Owner tag value for Azure resources
  environment_tag                       = "dev"                   # This is used on Azure tags as well as all resource names
  ip_address                            = "220.158.191.136"       # This is the ip address of the agent/current IP. Used to create firewall exemptions.
  deploy_sentinel                       = false
  deploy_purview                        = false      
  deploy_synapse                        = true
  is_vnet_isolated                      = false
  publish_web_app                       = true
  publish_function_app                  = true
  publish_sif                           = true
  publish_sample_files                  = true
  publish_database                      = true
  configure_networking                  = false
  publish_datafactory_pipelines         = true
  publish_web_app_addcurrentuserasadmin = true
  deploy_selfhostedsql                  = false
  is_onprem_datafactory_ir_registered   = false
  sif_database_name                     = "SIFMD"           #other variables aren't done this way
  skipTerraformDeployment		= false             #a case for deployment only needed resources without deleting previous
}
