inputs = {
  prefix                               = "ads"              # All azure resources will be prefixed with this
  domain                                = "moqdev.onmicrosoft.com"              # Used when configuring AAD config for Azure functions 
  tenant_id                             = "b938b10c-b509-4b5e-b5f8-84eff4d4c665"           # This is the Azure AD tenant ID
  subscription_id                       = "53fd48f8-99e9-459a-b2e6-5ad2107995bf"     # The azure subscription id to deploy to
  resource_location                     = "Australia East"        # The location of the resources
  resource_group_name                   = "sifmoqgo"          # The resource group all resources will be deployed to
  owner_tag                             = "lbravo"               # Owner tag value for Azure resources
  environment_tag                       = "dev"                   # This is used on Azure tags as well as all resource names
  ip_address                            = "220.158.191.2"          # This is the ip address of the agent/current IP. Used to create firewall exemptions.
  deploy_sentinel                       = false
  deploy_purview                        = false      
  deploy_synapse                        = true
  is_vnet_isolated                      = true
  publish_web_app                       = true
  publish_function_app                  = true
  publish_sample_files                  = true
  publish_database                      = true
  configure_networking                  = true
  publish_datafactory_pipelines         = true
  publish_web_app_addcurrentuserasadmin = true
  deploy_selfhostedsql                  = false
  is_onprem_datafactory_ir_registered   = false
}
