#original
TaskObject = "{\"TaskInstanceId\":1,\"TaskMasterId\":2,\"TaskStatus\":\"InProgress\",\"TaskType\":\"TestTask Type Name\",\"Enabled\":1,\"ExecutionUid\":\"8448eabb-9ba4-4779-865b-29e973431273\",\"NumberOfRetries\":0,\"DegreeOfCopyParallelism\":1,\"KeyVaultBaseUrl\":\"https://ark-stg-kv-ads-irud.vault.azure.net/\",\"ScheduleMasterId\":\"-4\",\"TaskGroupConcurrency\":\"10\",\"TaskGroupPriority\":0,\"TaskExecutionType\":\"ADF\",\"ExecutionEngine\":{\"EngineId\":-1,\"EngineName\":\"ark-stg-adf-ads-irud\",\"SystemType\":\"Datafactory\",\"ResourceGroup\":\"dlzdev04\",\"SubscriptionId\":\"ed1206e0-17c7-4bc2-ad4b-f8d4dab9284f\",\"ADFPipeline\":\"GPL_AzureSqlTable_NA_AzureBlobFS_Parquet_Azure\",\"EngineJson\":\"{}\",\"TaskDatafactoryIR\":\"Azure\",\"JsonProperties\":{}},\"Source\":{\"System\":{\"SystemId\":-8,\"SystemServer\":\"https://arkstgdlsadsirudadsl.dfs.core.windows.net\",\"AuthenticationType\":\"MSI\",\"Type\":\"ADLS\",\"Username\":null,\"Container\":\"datalakelanding\"},\"Instance\":{\"TargetRelativePath\":\"\"},\"DataFileName\":\"TestFile.parquet\",\"RelativePath\":\"\",\"SchemaFileName\":\"TestFile.json\",\"Type\":\"Parquet\"},\"Target\":{\"System\":{\"SystemId\":-8,\"SystemServer\":\"https://arkstgdlsadsirudadsl.dfs.core.windows.net\",\"AuthenticationType\":\"MSI\",\"Type\":\"ADLS\",\"Username\":null,\"Container\":\"datalakelanding\"},\"Instance\":{\"TargetRelativePath\":\"\"},\"DataFileName\":\"TestFile.parquet\",\"RelativePath\":\"\",\"SchemaFileName\":\"TestFile.json\",\"Type\":\"Parquet\"}}"


#//adsdevdlsadsic03adsl/synapse/sif/
#abfss://adsdevdlsadsic03@adsdevdlsadsic03adsl.blob.core.windows.net/synapse/sif
#dfs

#new
TaskObject = "{\"TaskInstanceId\":1,\"TaskMasterId\":2,\"TaskStatus\":\"InProgress\",\"TaskType\":\"TestTask Type Name\", \"Enabled\":1,\"ExecutionUid\":\"8448eabb-9ba4-4779-865b-29e973431273\",\"NumberOfRetries\":0,\"DegreeOfCopyParallelism\":1, \"KeyVaultBaseUrl\":\"https://ads-dev-kv-ads-ic038069.vault.azure.net/\",\"ScheduleMasterId\":\"-4\",\"TaskGroupConcurrency\":\"10\", \"TaskGroupPriority\":0,\"TaskExecutionType\":\"ADF\",\"ExecutionEngine\":{\"EngineId\":-1,\"EngineName\":\"ads-dev-kv-ads-ic038069\", \"SystemType\":\"Microsoft.Synapse/workspaces\",\"ResourceGroup\":\"sifgofast\",\"SubscriptionId\":\"cd486ba9-eef3-466d-b16c-7f1b2941ae9d\", \"ADFPipeline\":\"GPL_AzureSqlTable_NA_AzureBlobFS_Parquet_Azure\",\"EngineJson\":\"{}\",\"TaskDatafactoryIR\":\"Azure\", \"JsonProperties\":{}},\"Source\":{\"System\":{\"SystemId\":-8,\"SystemServer\":\"abfss://adsdevdlsadsic03adsl.dfs.core.windows.net\", \"AuthenticationType\":\"MSI\",\"Type\":\"ADLS\",\"Username\":null,\"Container\":\"adsdevdlsadsic03\"},\"Instance\":{\"TargetRelativePath\":\"\"}, \"DataFileName\":\"StudentPersonal.json\",\"SourceRelativePath\":\"synapse/sif\",\"SchemaFileName\":\"StudentPersonal.json\",\"Type\":\"Json\"}, \"Target\":{\"System\":{\"SystemId\":-8,\"SystemServer\":\"https://adsdevdlsadsic03adsl.blob.core.windows.net\", \"AuthenticationType\":\"MSI\",\"Type\":\"ABS\",\"Username\":null,\"Container\":\"adsdevdlsadsic03\"}, \"Instance\":{\"TargetRelativePath\":\"synapse/stage2/sif\"},\"DataFileName\":\"StudentPersonal\",\"RelativePath\":\"\", \"SchemaFileName\":\"StudentPersonal.json\",\"Type\":\"Delta\"}}"
